### ISSUE TITLE
Syntax recognition patch (diff)

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/extensions#802] opened 2024-05-28 18:37 UTC
### Check for existing issues

- [X] Completed

### Misc notes

Vscode:
<img width="888" alt="Screenshot 2024-05-28 alle 20 36 23" src="https://github.com/zed-industries/extensions/assets/20476002/153b0736-ef61-40ae-b75d-4c9238a98baa">
Zed:
<img width="885" alt="Screenshot 2024-05-28 alle 20 36 31" src="https://github.com/zed-industries/extensions/assets/20476002/124b19b1-6a86-44df-a6fd-b4593bfb9c99">

**Comment by Moshyfawn** [comment] 2024-05-28 18:51
There's already a request for this, so I'm going to close this issue in favour of the other one. Be sure to +👍 the other thread as well as add any missing information to it.

Duplicate of:
- #490

**Closed by Moshyfawn** 2024-05-28 18:51 UTC
Labels: needs infrastructure
