### ISSUE TITLE
XML

### ISSUE THREAD

**Issue by wzxu** [zed-industries/extensions#161] opened 2023-03-27 06:56 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Zed currently already supports syntax highlighting for HTML. Should be low hanging fruit to extend it to support XML.

**Comment by thbar** [comment] 2024-03-24 22:16
If you need a large XML file for testing, here is one :smile: https://www.data.gouv.fr/fr/datasets/cheminements-pietons-dans-paris-dapres-openstreetmap/

**Comment by mileusna** [comment] 2024-03-26 19:44
> If you need a large XML file for testing, here is one 😄 https://www.data.gouv.fr/fr/datasets/cheminements-pietons-dans-paris-dapres-openstreetmap/

🤫 Zed can't even open 500K - 1MB files.

**Comment by thbar** [comment] 2024-03-26 19:49
> 🤫 Zed can't even open 500K - 1MB files.

It seems to open that 431MB file just fine here, after just a few seconds of loading. Not too shabby!

![CleanShot 2024-03-26 at 20 48 49@2x](https://github.com/zed-industries/extensions/assets/10141/421cafc0-2f78-4689-8d5b-fe2db9a4f4e9)

**Comment by mileusna** [comment] 2024-03-26 20:39
> > 🤫 Zed can't even open 500K - 1MB files.
> 
> It seems to open that 431MB file just fine here, after just a few seconds of loading. Not too shabby!

Strange, it works with this enormous XML file, but still can't open my 2.9MB .txt file. Looks like I will have to open new issue.

This is what I get compared to Sublime Text:

<img width="1479" alt="Screenshot 2024-03-26 at 21 37 58" src="https://github.com/zed-industries/extensions/assets/4697935/7e9a803c-155f-465e-851f-0de65ea642d2">

**Comment by thbar** [comment] 2024-03-26 22:22
@mileusna are you able to share the file for a reproduction ? Maybe it's related to platform-specific bits (I'm on Mac M1).

**Comment by mileusna** [comment] 2024-03-26 23:22
> @mileusna are you able to share the file for a reproduction ? Maybe it's related to platform-specific bits (I'm on Mac M1).

I have opened the issue, here you can find everything, including the file.

https://github.com/zed-industries/zed/issues/9833

**Comment by sweetppro** [comment] 2024-04-25 05:15
XML support is available now in  the XML extension
https://github.com/zed-industries/extensions/pull/590
https://github.com/sweetppro/zed-xml

**Comment by lacastorine** [comment] 2024-05-08 11:07
Could you pls add also support for `*.xsl` files?

**Comment by sweetppro** [comment] 2024-05-08 17:25
you can add something like this to your settings:

```
"file_types": {
    "XML": ["xsl"]
  }
```

**Comment by maxdeviant** [comment] 2024-05-23 18:32
Closing this issue, since the XML extension is now available.

**Closed by maxdeviant** 2024-05-23 18:32 UTC
Labels: language

**Comment by maryisdead** [comment] 2024-06-26 07:34
Just wanna say that it feels very weird to have one of the most common markup languages on the planet not supported out of the box.

**Comment by uncenter** [comment] 2024-12-11 14:52
> Just wanna say that it feels very weird to have one of the most common markup languages on the planet not supported out of the box.

I mean you could probably raise a PR to include it by default? Wouldn't be much work outside of copying over the files from the extension.

**Comment by nikitakalnov** [comment] 2025-04-20 23:12
The XML extension - https://github.com/sweetppro/zed-xml - gives just a little bit of functionality, just a syntax highlight. There is still no bracket matching and folding features in XML files.
