### ISSUE TITLE
when do we expect language support for ANGULAR with TypeScript  in zed.dev?

### ISSUE THREAD

**Issue by tsuryatej** [zed-industries/extensions#1714] opened 2024-11-26 08:24 UTC
### Check for existing issues

- [X] Completed

### Language

Angular

### Misc notes

when do we expect language support for angular in zed.dev

**Comment by Moshyfawn** [comment] 2024-11-27 02:04
Duplicate of:
- #169

**Closed by Moshyfawn** 2024-11-27 02:04 UTC
Labels: language
