### ISSUE TITLE
Git merge-resolver

### ISSUE THREAD

**Issue by yyyxam** [zed-industries/extensions#1739] opened 2024-12-02 16:37 UTC
### Check for existing issues

- [X] Completed

### Misc notes

Really loving Zed so far.
I would really like a UI tool for fixing merge conflicts as present in VScode or Jetbrains' editors. Specifically [Jetbrains](https://resources.jetbrains.com/help/img/idea/2024.3/conflict_resolution_tool_legend_dark.png) has a beautiful solution for this which I would love to see in Zed.

**Comment by Moshyfawn** [comment] 2024-12-02 17:08
There's a fairly well-known feature request for this in the core repository, so I'm going to close this in favor of the existing one. Please be sure to +👍 to show your support.

Duplicate of:
- zed-industries/zed#4269

**Closed by Moshyfawn** 2024-12-02 17:08 UTC
Labels: needs infrastructure
