### ISSUE TITLE
`request feature` Add support for Mojo 🔥 programming language

### ISSUE THREAD

**Issue by mmenendezg** [zed-industries/extensions#1011] opened 2024-07-08 13:16 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Add Mojo🔥 to the list of supported languages in Zed.

**Comment by JosephTLyons** [comment] 2024-07-08 17:57
Hey @mmenendezg,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/extensions/issues/731

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-07-08 17:57 UTC
Labels: language
