### ISSUE TITLE
Perl syntax recognition

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/extensions#874] opened 2024-06-05 12:54 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

<img width="774" alt="Screenshot 2024-06-05 alle 14 54 01" src="https://github.com/zed-industries/zed/assets/20476002/ed2f46f4-2514-4fb7-8264-0e734ad7a369">

**Comment by JosephTLyons** [comment] 2024-06-05 20:26
Hey @Angelk90 ,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/extensions/issues/874

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-06-05 20:26 UTC
Labels: language
