### ISSUE TITLE
Highlights for cobol programming language

### ISSUE THREAD

**Issue by Seidon1984** [zed-industries/extensions#585] opened 2024-04-19 05:15 UTC
### Check for existing issues

- [X] Completed

### Language

Cobol

**Comment by JosephTLyons** [comment] 2024-07-16 17:45
Hey @Seidon1984,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/extensions/issues/132

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-07-16 17:45 UTC
Labels: language
