### ISSUE TITLE
Ruby auto-indentation doesn't always work

### ISSUE THREAD

**Issue by janko** [zed-industries/extensions#794] opened 2024-05-28 11:29 UTC
### Check for existing issues

- [X] Completed

### Misc notes

If I write:

```
def foo
end
```

and I go to the end of `foo` and type `<Enter>`, my cursor ends up here

```
def foo
*
end
```

instead of here

```
def foo
  *
end
```

**Comment by Moshyfawn** [comment] 2024-05-28 15:01
I believe this has already been reported in the Zed repository, so I'll close this issue. Be sure to +👍 the other thread.

In the future, please consider creating an extension-related issue in the extension's own community repository, or if it's an extension maintained by the Zed team, in the main Zed repository instead.

Duplicate of:
- zed-industries/zed#4479

**Closed by Moshyfawn** 2024-05-28 15:01 UTC
Labels: needs infrastructure

**Comment by Moshyfawn** [comment] 2024-05-28 15:08
No problem at all and thanks!
