### ISSUE TITLE
Kindly Finally Add FLUTTER support

### ISSUE THREAD

**Issue by fisforfaheem** [zed-industries/extensions#1024] opened 2024-07-11 17:33 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Millions of developers want flutter on ZED please bring it here.

**Comment by SomeoneToIgnore** [comment] 2024-07-11 17:40
Duplicate of https://github.com/zed-industries/extensions/issues/247

**Closed by SomeoneToIgnore** 2024-07-11 17:40 UTC
